vlans:
- name: ETHERNET-VPN-IRB-1103
  id: 1103
- name: ETHERNET-VPN-L2VLAN-1199
  id: 1199
- name: VPWS-1401
  id: 1401

ethernet_interfaces:
  - name: Ethernet1
    description: to s1-pe02 ethernet4
    # vlans: "1-4094"
    switchport:
      enabled: True
      mode: "trunk"
      trunk:
        allowed_vlan: '1-4094'

  - name: Ethernet2
    switchport:
      enabled: false
    peer_type: l3_interface
    shutdown: false

  - name: Ethernet2.101
    peer_type: l3_interface
    ip_address: 10.2.0.1/31
    shutdown: false
    description: L3VPN Only USE CASE
    encapsulation_dot1q:
      vlan: 101
    vrf: ATM

  - name: Ethernet3
    description: to s1-pe03 ethernet6
    # vlans: "1-4094"
    switchport:
      enabled: True
      mode: "trunk"
      trunk:
        allowed_vlan: '1-4094'


port_channel_interfaces:

vlan_interfaces:
  - name: "Vlan1103"
    description: vrf-irb-vlan1101
    shutdown: False
    vrf: IRB
    ip_address: "10.1.3.{{ device_id }}/24"

  - name: "Vlan1199"
    description: vrf-irb-vlan1199
    shutdown: False
    vrf: L2VLAN
    ip_address: "10.1.99.{{ device_id }}/24"

  - name: "Vlan1401"
    description: vrf-vpws
    shutdown: False
    vrf: VPWS
    ip_address: "10.4.1.{{ device_id }}/24"

static_routes:
  - vrf: "{{ management_vrf_name }}"
    destination_address_prefix: 0.0.0.0/0
    gateway: 192.168.2.1
  - vrf: IRB
    destination_address_prefix: 10.1.0.0/16
    gateway: 10.1.3.1
  - vrf: ATM
    destination_address_prefix: 10.2.254.0/24
    interface: Null0

router_bgp:
  as: '65101'
  updates:
    wait_install: false
  peer_groups:
  - name: MPLS-BACKBONE
    remote_as: '65000'
    description: MPLS CONNECTITVITY
    shutdown: false
    bfd: false
    send_community: all
  vrfs:
  - name: ATM
    redistribute:
      connected:
        enabled: true
      static:
        enabled: true
    address_family_ipv4:
      neighbors:
      - ip_address: 10.2.0.0
        activate: true
    neighbors:
    - ip_address: 10.2.0.0
      peer_group: MPLS-BACKBONE
      description: MPLS CONNECTITVITY S1-PE03
      route_map_out: RM-MARK-ATM-CE03
    updates:
      wait_install: false

prefix_lists:
  - name: PL-ATM-FAKE-PREFIX
    sequence_numbers:
      - sequence: 10
        action: "permit 10.2.254.0/24"

route_maps:
    # Route-map Name.
  - name: RM-MARK-ATM-CE03
    sequence_numbers:
      - sequence: 10
        type: permit
        description: Mark FAKE route with community 65000:12013
        # match:
        #   - "ip address prefix-list PL-ATM-FAKE-PREFIX"
        set:
          - "community 65000:10090 additive"