tenants:
  # Definition of tenants. Additional level of abstraction to VRFs
  - name: ETHERNET_VPN
    mac_vrf_vni_base: 10000
    vrfs:
      - name: 'IRB'
        # Supernetwork is: 10.1.0.0/16
        vrf_id: 11
        address_families:
          - evpn
        vtep_diagnostic:
          loopback: 1011
          loopback_description: ETHERNET_VPN_IRB
          loopback_ip_range: 10.1.255.0/24
        svis:
          - id: 1101
            name: ETHERNET_VPN_IRB_S1_CE01-02
            enabled: True
            ip_address_virtual: 10.1.1.1/24
            tags: ['node01', 'node02']

          - id: 1103
            name: ETHERNET_VPN_IRB_S1_CE03
            enabled: True
            ip_address_virtual: 10.1.3.1/24
            tags: ['node03']
    l2vlans:
      - id: 1199
        name: ETHERNET_VPN_L2VLAN
        tags: ['node01', 'node02', 'node03']
        vxlan: True

  - name: FIREWALL
    mac_vrf_vni_base: 13000
    vrfs:
      - name: 'FW'
        # Supernetwork is: 10.3.0.0/16
        vrf_id: 13
        address_families:
          - evpn
        vtep_diagnostic:
          loopback: 1013
          loopback_description: SVC_FIREWALL_LOOPBACK
          loopback_ip_range: 10.3.255.0/24
        svis:
          - id: 1301
            name: FIREWALL-BGP-EXIT-S1-NORTH
            enabled: True
            ip_virtual_router_addresses:
              - 10.3.1.1
            nodes:
              - node: a-pe01
                ip_address: 10.3.1.2/24
              - node: s1-pe02
                ip_address: 10.3.1.3/24
            tags: ['node01', 'node02']
        bgp_peers:
          - ip_address: 10.3.1.11
            remote_as: 65103
            update_source: Loopback1013
            peer_group: FIREWALL-BGP
            description: FIREWALL-BGP a-ce01
            send_community: "standard extended"
            ebgp_multihop: 10
            nodes: [ a-pe01, s1-pe02 ]

  - name: L3VPN_Only
    mac_vrf_vni_base: 12000
    vrfs:
      - name: 'ATM'
        # Supernetwork is: 10.2.0.0/16
        vrf_id: 12
        address_families:
          - evpn
        vtep_diagnostic:
          loopback: 1012
          loopback_description: SVC_ETHERNET_LOOPBACK
          loopback_ip_range: 10.2.255.0/24
        svis:
          - id: 1205
            name: L3VPN-EXIT-POINT
            enabled: True
            ip_address: 10.2.1.1/24
            tags: ['site02']
            ospf:
              enabled: True
              point_to_point: True
              area: 0.0.0.0
        l3_interfaces:
          # L3 interfaces
          - interfaces: [ Ethernet5.101, Ethernet5.101 ]
            nodes: [ s1-pe03, s1-pe04 ]
            description: L3VPN Only USE CASE
            enabled: true
            ip_addresses: [ 10.2.0.0/31, 10.2.0.2/31]
        ospf:
          enabled: True
          process_id: 1205
          redistribute_bgp:
            enabled: True
            route_map: RM-BGP-TO-OSPF
        bgp_peers:
          - ip_address: 10.2.0.1
            peer_group: ATM-BACKBONE
            description: ATM CONNECTITVITY S1-CE03
            remote_as: 65101
            nodes: [ s1-pe03 ]
          - ip_address: 10.2.0.3
            peer_group: ATM-BACKBONE
            description: ATM CONNECTITVITY S1-CE04
            remote_as: 65101
            nodes: [ s1-pe04 ]
          # - ip_address: 10.2.1.21
          #   peer_group: ATM-BACKBONE
          #   description: ATM CONNECTITVITY b-ce01
          #   remote_as: 65102
          #   nodes: [ b-pe01 ]
        bgp_peer_groups:
          - name: ATM-BACKBONE
            nodes:
              - s1-pe03
              - s1-pe04
              # - b-pe01
            address_family_ipv4:
              activate: True
            description: ATM CONNECTITVITY
            shutdown: False
            bfd: False

  - name: VPWS
    pseudowire_rt_base: 14000
    point_to_point_services:
        # Pseudowire name.
      - name: s1-ce03-s1-ce04
        type: "vpws-pseudowire"
        # Pseudowire terminating endpoints. Must have exactly two items.
        endpoints:
          - id: 3
            nodes:
              - s1-pe03
            interfaces:
              - eth6
          - id: 4
            nodes:
              - s1-pe04
            interfaces:
              - eth6
        lldp_disable: True