---
- name: Load Network Device Configs
  hosts: all
  gather_facts: no
  tasks:
    - name: Arista Config Load
      arista.eos.eos_config:
        src: "../l3vpn-configs/{{ inventory_hostname }}.cfg"
        replace: config



