hostname: "{{ inventory_hostname }}"

management_interfaces:
  - name: Management0
    description: oob_management
    shutdown: false
    vrf: "{{ management_vrf_name }}"
    ip_address: "{{ ansible_host }}/24"
    gateway: 192.168.2.1
    type: oob

# Static routes within Management VRF
static_routes:


service_routing_protocols_model: multi-agent
ip_routing: true

vrfs:
  - name: default
    ip_routing: true
  - name: "{{ management_vrf_name }}"
    ip_routing: true
  - name: 'ETHERNET_VPN'
    ip_routing: true
  - name: ATM
    tenant: L3VPN_Only
    ip_routing: true
  - name: IRB
    tenant: ETHERNET_VPN_IRB
    ip_routing: true
  - name: L2VLAN
    tenant: ETHERNET_VPN_IRB
    ip_routing: true
  - name: FW
    tenant: FIREWALL-BGP
    ip_routing: true
  - name: VPWS
    tenant: VPWS-service
    ip_routing: False