platform_settings:
  - feature_support:
      bgp_update_wait_for_convergence: false
      bgp_update_wait_install: false
      interface_storm_control: false
      queue_monitor_length_notify: false
    management_interface: Management0
    platforms:
    - CEOS
    - cEOS
    - ceos
    - cEOSLab
    reload_delay:
      mlag: 300
      non_mlag: 330
